name: "Run Build Test"
on:
  push:
    branches:
      - pr@*
      - repr@*
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: jumpserver/web-static:test
        build-args: |
          APT_MIRROR=http://deb.debian.org
        file: Dockerfile
        cache-from: type=gha
        cache-to: type=gha,mode=max
