name: "Run Build Test"
on:
  push:
    branches:
      - pr@*
      - repr@*
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3

    - name: Prepare files
      run: |
        bash prepare.sh
    
    - name: Get pip_package.zip
      run: |
        applets_version=$(curl -s https://api.github.com/repos/jumpserver/applets/releases/latest | grep "tag_name" | awk '{print $2}' | sed 's/"//g' | sed 's/,//g')
        wget -qO opt/download/applets/pip_packages.zip https://github.com/jumpserver/applets/releases/download/${applets_version}/pip_packages.zip
  
    - name: Get binaries
      run: |
        bash tools.sh

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: false
        tags: jumpserver/web-static:test
        file: Dockerfile
        outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
        cache-from: type=gha
        cache-to: type=gha,mode=max
